name: GlowstoneLanterns
main: com.timvisee.glowstonelanterns.GlowstoneLanterns
version: ${project.version}
description: 'Make glowstone lanterns, daytime glass & nighttime glowstone!'
author: timvisee
website: http://timvisee.com/
softdepend:
    - PermissionsEx
    - PermissionsBukkit
    - bPermissions
    - EssentialsGroupManager
    - zPermissions
    - Vault
    - Permissions
commands:
  glowstonelantern:
    description: Toggle Glowstone Lanterns
    usage: /glowstonelantern
  glowstonelanterns:
    description: Toggle Glowstone Lanterns
    usage: /glowstonelanterns
  gl:
    description: Toggle Glowstone Lanterns
    usage: /gl
